return
{
	{"levelequals", 1},
	{"fadeIn", 0.2},
	{"spawncharacter", {"idiot"}},
	{"freezeplayer"},
	{"dialog", {"idiot", "Argh.. where.. am I?"}},
	{"sleep", 0.1},
	{"sleep", 1},
	{"dialog", {"idiot", "Oh, what the..! Dammit!"}},
	{"usedoor", {352, 192}},
	{"sleep", 0.4},
	{"spawncharacter", {"ren", 352, 211, "top"}},
	{"walkcharacter", {"ren", "left", 220}},
	{"sleep", 0.2},
	{"usedoor", {352, 192}},
	{"sleep", 2.5},
	{"dialog", {"ren", "Good job, Idiot. You fell for that one."}},
	{"dialog", {"idiot", "Hey! What is this about?!"}},
	{"dialog", {"ren", "Nyeheheh."}},
	{"dialog", {"idiot", "Oh when I get out of here, you're dead, Ren!"}},
	{"dialog", {"ren", "Hah I'm not scared of you."}},
	{"dialog", {"idiot", "Gah! You little!"}},
	{"walkcharacter", {"ren", "right", 320}},
	{"sleep", 0.2},
	{"spawnobject", {"key", 120, 204}},
	{"sleep", 2.5},
	{"usedoor", {352, 192}},
	{"sleep", 0.2},
	{"removecharacter", {"ren"}},
	{"unfreezeplayer"},
	{"sleep", 0.2},
	{"usedoor", {352, 192}}
}