return
{
    {"levelequals", 18},
    {"freezeplayer"},
    {"stopmusic"},
    {"fadein", 1},
    {"spawncharacter", {"idiot"}},
    {"spawncharacter", {"turtle", 224, 188, "top", true}},
    {"walkcharacter", {"idiot", "right", 164}},
    {"sleep", 1},
    {"dialog", {"turtle", "Huff . . Huff . ."}},
    {"sleep", 1},
    {"dialog", {"idiot", "How are you still alive?!"}},
    {"sleep", 1},
    {"dialog", {"turtle", "Please . . forgive me! I never intended to--"}},
    {"sleep", 0.5},
    {"dialog", {"idiot", ". . ."}},
    {"sleep", 1},
    {"dialog", {"idiot", "Screw you, Turtle."}},
    {"sleep", 1},
    {"walkcharacter", {"idiot", "right", 300}},
    {"dialog", {"idiot", "Remember to close the door behind you, idiot.", true}},
    {"sleep", 1},
    {"fadeout", 1},
    {"sleep", 1},
    {"nextlevel"}
}